jellyfinNetwork:
  webPort: 31000

jellyfinRunAs:
  user: 1000
  group: 1000
  supplementalGroups: 
    -44

jellyfinStorage:
  config:
    type: pvc
  cache:
    type: pvc
  transcodes:
    type: emptyDir
    emptyDirConfig:
      medium: Memory
      size: 1
  securityContext:
    privileged: true

# Make sure installation don't fail when 0 GPU are assigned
jellyfinGPU:
  nvidia.com/gpu: 0
  intel.com/gpu: 44
# TODO: Test assigning GPUs on a GPU-enabled system
